language: common-lisp

addons:
  postgresql: "9.3"

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - mysql -uroot -e 'GRANT ALL ON *.* TO nobody@"localhost" IDENTIFIED BY "nobody"'
  - mysql -e 'CREATE DATABASE `cl-dbi`'
  - psql -c 'create database "cl-dbi";' -U postgres
  - psql -c "CREATE USER nobody WITH PASSWORD 'nobody';" -U postgres

script:
  - cl -l prove -e '(or (prove:run :dbi-test) (uiop:quit -1))'
